
if Not Exists(Select 1 from Countries)
Begin
	SET IDENTITY_INSERT countries ON;

	INSERT INTO Countries (id, Name_en, Name_ar, code, iso3) VALUES
	(1, 'Andorra', 'أندورا','AD', 'AND'),
	(2, 'United Arab Emirates', 'المتحدة العربية الإمارات ', 'AE', 'ARE'),
	(3, 'Afghanistan', 'أفغانستان',  'AF', 'AFG'),
	(4, 'Antigua and Barbuda', 'أنتيغوا وبربودا ',  'AG', 'ATG'),
	(5, 'Anguilla', 'أنغويلا',  'AI', 'AIA'),
	(6, 'Albania', 'ألبانيا',  'AL', 'ALB'),
	(7, 'Armenia', 'أرمينيا',  'AM', 'ARM'),
	(8, 'Netherlands Antilles', 'جزر الأنتيل الهولندية',  'AN', 'ANT'),
	(9, 'Angola', 'أنغولا',  'AO', 'AGO'),
	(10, 'Antarctica', 'القارة القطبية الجنوبية', 'AQ', 'ATA'),
	(11, 'Argentina', 'الأرجنتين',  'AR', 'ARG'),
	(12, 'American Samoa', 'ساموا الأمريكية',  'AS', 'ASM'),
	(13, 'Austria', 'النمسا',  'AT', 'AUT'),
	(14, 'Australia', 'أستراليا', 'AU', 'AUS'),
	(15, 'Aruba', 'أروبا', 'AW', 'ABW'),
	(16, 'Åland', 'جزر أولاند', 'AX', 'ALA'),
	(17, 'Azerbaijan', 'أذربيجان', 'AZ', 'AZE'),
	(18, 'Bosnia and Herzegovina', 'والهرسك البوسنة ','BA', 'BIH'),
	(19, 'Barbados', 'بربادوس', 'BB', 'BRB'),
	(20, 'Bangladesh', 'بنغلاديش', 'BD', 'BGD'),
	(21, 'Belgium', 'بلجيكا', 'BE', 'BEL'),
	(22, 'Burkina Faso', 'بوركينا فاسو ', 'BF', 'BFA'),
	(23, 'Bulgaria', 'بلغاريا', 'BG', 'BGR'),
	(24, 'Bahrain', 'البحرين', 'BH', 'BHR'),
	(25, 'Burundi', 'بوروندي', 'BI', 'BDI'),
	(26, 'Benin', 'بنن', 'BJ', 'BEN'),
	(27, 'Saint Barthélemy', 'سان بارتيلمي', 'BL', 'BLM'),
	(28, 'Bermuda', 'برمودا','BM', 'BMU'),
	(29, 'Brunei Darussalam', 'السلام دار برونى ', 'BN', 'BRN'),
	(30, 'Bolivia', 'بوليفيا - دولة - المتعددة القوميات ','BO', 'BOL'),
	(31, 'Brazil', 'البرازيل','BR', 'BRA'),
	(32, 'Bahamas', 'البهاما جزر ','BS', 'BHS'),
	(33, 'Bhutan', 'بوتان','BT', 'BTN'),
	(34, 'Bouvet Island', 'جزيرة بوفيه', 'BV', 'BVT'),
	(35, 'Botswana', 'بوتسوانا','BW', 'BWA'),
	(36, 'Belarus', 'بيلاروس','BY', 'BLR'),
	(37, 'Belize', 'بليز','BZ', 'BLZ'),
	(38, 'Canada', 'كندا','CA', 'CAN'),
	(39, 'Cocos (Keeling) Islands', 'جزر كوكوس', 'CC', 'CCK'),
	(40, 'Congo (Kinshasa)', 'الديمقراطية الكونغو جمهورية ',  'CD', 'COD'),
	(41, 'Central African Republic', 'الوسطى أفريقيا جمهورية ', 'CF', 'CAF'),
	(42, 'Congo (Brazzaville)', 'الكونغو','CG', 'COG'),
	(43, 'Switzerland', 'سويسرا','CH', 'CHE'),
	(44, 'Côte d''Ivoire', 'ديفوار كوت ', 'CI', 'CIV'),
	(45, 'Cook Islands', 'كوك جزر ', 'CK', 'COK'),
	(46, 'Chile', 'شيلى','CL', 'CHL'),
	(47, 'Cameroon', 'الكاميرون','CM', 'CMR'),
	(48, 'China', 'الصين',  'CN', 'CHN'),
	(49, 'Colombia', 'كولومبيا',  'CO', 'COL'),
	(50, 'Costa Rica', 'كوستاريكا', 'CR', 'CRI'),
	(51, 'Cuba', 'كوبا', 'CU', 'CUB'),
	(52, 'Cape Verde', 'كابو فيردي ', 'CV', 'CPV'),
	(53, 'Christmas Island', 'جزيرة عيد الميلاد', 'CX', 'CXR'),
	(54, 'Cyprus', 'قبرص', 'CY', 'CYP'),
	(55, 'Czech Republic', 'التشيكية الجمهورية ',  'CZ', 'CZE'),
	(56, 'Germany', 'ألمانيا', 'DE', 'DEU'),
	(57, 'Djibouti', 'جيبوتي', 'DJ', 'DJI'),
	(58, 'Denmark', 'الدانمرك', 'DK', 'DNK'),
	(59, 'Dominica', 'دومينيكا', 'DM', 'DMA'),
	(60, 'Dominican Republic', 'الجمهورية الدومينيكية ',  'DO', 'DOM'),
	(61, 'Algeria', 'الجزائر', 'DZ', 'DZA'),
	(62, 'Ecuador', 'إكوادور', 'EC', 'ECU'),
	(63, 'Estonia', 'إستونيا', 'EE', 'EST'),
	(64, 'Egypt', 'مصر', 'EG', 'EGY'),
	(65, 'Western Sahara', 'الصحراء الغربية',  'EH', 'ESH'),
	(66, 'Eritrea', 'إريتريا', 'ER', 'ERI'),
	(67, 'Spain', 'إسبانيا', 'ES', 'ESP'),
	(68, 'Ethiopia', 'إثيوبيا', 'ET', 'ETH'),
	(69, 'Finland', 'فنلندا', 'FI', 'FIN'),
	(70, 'Fiji', 'فيجي',  'FJ', 'FJI'),
	(71, 'Falkland Islands', 'جزر فوكلاند',  'FK', 'FLK'),
	(72, 'Micronesia', 'ميكرونيزيا',  'FM', 'FSM'),
	(73, 'Faroe Islands', 'جزر فيرويه ', 'FO', 'FRO'),
	(74, 'France', 'فرنسا',  'FR', 'FRA'),
	(75, 'Gabon', 'غابون',  'GA', 'GAB'),
	(76, 'United Kingdom', 'المملكة المتحدة ',  'GB', 'GBR'),
	(77, 'Grenada', 'غرينادا',  'GD', 'GRD'),
	(78, 'Georgia', 'جورجيا',  'GE', 'GEO'),
	(79, 'French Guiana', 'غويانا الفرنسية',  'GF', 'GUF'),
	(80, 'Guernsey', 'غيرنزي',  'GG', 'GGY'),
	(81, 'Ghana', 'غانا',  'GH', 'GHA'),
	(82, 'Gibraltar', 'جبل طارق',  'GI', 'GIB'),
	(83, 'Greenland', 'جرينلاند',  'GL', 'GRL'),
	(84, 'Gambia', 'غامبيا',  'GM', 'GMB'),
	(85, 'Guinea', 'غينيا',  'GN', 'GIN'),
	(86, 'Guadeloupe', 'غوادلوب',  'GP', 'GLP'),
	(87, 'Equatorial Guinea', 'الاستوائية غينيا ', 'GQ', 'GNQ'),
	(88, 'Greece', 'اليونان',  'GR', 'GRC'),
	(89, 'South Georgia and South Sandwich Islands', 'جورجيا الجنوبية وجزر ساندويتش الجنوبية',  'GS', 'SGS'),
	(90, 'Guatemala', 'غواتيمالا',  'GT', 'GTM'),
	(91, 'Guam', 'غوام',  'GU', 'GUM'),
	(92, 'Guinea-Bissau', 'غينيا - بيساو ', 'GW', 'GNB'),
	(93, 'Guyana', 'غيانا', 'GY', 'GUY'),
	(94, 'Hong Kong', 'هونغ كونغ', 'HK', 'HKG'),
	(95, 'Heard and McDonald Islands', 'جزيرة هيرد وجزر ماكدونالد', 'HM', 'HMD'),
	(96, 'Honduras', 'هندوراس', 'HN', 'HND'),
	(97, 'Croatia', 'كرواتيا', 'HR', 'HRV'),
	(98, 'Haiti', 'هايتي', 'HT', 'HTI'),
	(99, 'Hungary', 'هنغاريا', 'HU', 'HUN'),
	(100, 'Indonesia', 'إندونيسيا', 'ID', 'IDN'),
	(101, 'Ireland', 'آيرلندا', 'IE', 'IRL'),
	(102, 'Israel', 'إسرائيل', 'IL', 'ISR'),
	(103, 'Isle of Man', 'جزيرة مان', 'IM', 'IMN'),
	(104, 'India', 'الهند', 'IN', 'IND'),
	(105, 'British Indian Ocean Territory', 'إقليم المحيط الهندي البريطاني', 'IO', 'IOT'),
	(106, 'Iraq', 'العراق', 'IQ', 'IRQ'),
	(107, 'Iran', 'الإسلامية - جمهورية - إيران ', 'IR', 'IRN'),
	(108, 'Iceland', 'آيسلندا', 'IS', 'ISL'),
	(109, 'Italy', 'إيطاليا', 'IT', 'ITA'),
	(110, 'Jersey', 'جيرزي', 'JE', 'JEY'),
	(111, 'Jamaica', 'جامايكا', 'JM', 'JAM'),
	(112, 'Jordan', 'الأردن', 'JO', 'JOR'),
	(113, 'Japan', 'اليابان', 'JP', 'JPN'),
	(114, 'Kenya', 'كينيا', 'KE', 'KEN'),
	(115, 'Kyrgyzstan', 'قيرغيزستان', 'KG', 'KGZ'),
	(116, 'Cambodia', 'كمبوديا', 'KH', 'KHM'),
	(117, 'Kiribati', 'كيريباس', 'KI', 'KIR'),
	(118, 'Comoros', 'جزر القمر ', 'KM', 'COM'),
	(119, 'Saint Kitts and Nevis', 'ونيفيس كيتس سانت ','KN', 'KNA'),
	(120, 'Korea, North', 'الديمقراطية الشعبية كوريا جمهورية ', 'KP', 'PRK'),
	(121, 'Korea, South', 'جمهورية كوريا ','KR', 'KOR'),
	(122, 'Kuwait', 'الكويت', 'KW', 'KWT'),
	(123, 'Cayman Islands', 'جزر كايمان','KY', 'CYM'),
	(124, 'Kazakhstan', 'كازاخستان', 'KZ', 'KAZ'),
	(125, 'Laos', 'الشعبية الديمقراطية لاو جمهورية ', 'LA', 'LAO'),
	(126, 'Lebanon', 'لبنان', 'LB', 'LBN'),
	(127, 'Saint Lucia', 'لوسيا سانت ', 'LC', 'LCA'),
	(128, 'Liechtenstein', 'لختنشتاين', 'LI', 'LIE'),
	(129, 'Sri Lanka', 'سري لانكا ', 'LK', 'LKA'),
	(130, 'Liberia', 'ليبريا', 'LR', 'LBR'),
	(131, 'Lesotho', 'ليسوتو', 'LS', 'LSO'),
	(132, 'Lithuania', 'ليتوانيا', 'LT', 'LTU'),
	(133, 'Luxembourg', 'لكسمبرغ', 'LU', 'LUX'),
	(134, 'Latvia', 'لاتفيا', 'LV', 'LVA'),
	(135, 'Libya', 'ليبيا', 'LY', 'LBY'),
	(136, 'Morocco', 'المغرب', 'MA', 'MAR'),
	(137, 'Monaco', 'موناكو', 'MC', 'MCO'),
	(138, 'Moldova', 'جمهورية مولدوفا ', 'MD', 'MDA'),
	(139, 'Montenegro', 'الأسود الجبل ', 'ME', 'MNE'),
	(140, 'Saint Martin (French part)', 'تجمع سان مارتين','MF', 'MAF'),
	(141, 'Madagascar', 'مدغشقر', 'MG', 'MDG'),
	(142, 'Marshall Islands', 'جزر مارشال ','MH', 'MHL'),
	(143, 'Macedonia', 'جمهورية مقدونيا اليوغوسلافية السابقة ', 'MK', 'MKD'),
	(144, 'Mali', 'مالي', 'ML', 'MLI'),
	(145, 'Myanmar', 'ميانمار', 'MM', 'MMR'),
	(146, 'Mongolia', 'منغوليا', 'MN', 'MNG'),
	(147, 'Macau', 'ماكاو', 'MO', 'MAC'),
	(148, 'Northern Mariana Islands', 'جزر ماريانا الشمالية', 'MP', 'MNP'),
	(149, 'Martinique', 'مارتينيك', 'MQ', 'MTQ'),
	(150, 'Mauritania', 'موريتانيا', 'MR', 'MRT'),
	(151, 'Montserrat', 'مونتسرات', 'MS', 'MSR'),
	(152, 'Malta', 'مالطة', 'MT', 'MLT'),
	(153, 'Mauritius', 'موريشيوس', 'MU', 'MUS'),
	(154, 'Maldives', 'ملديف', 'MV', 'MDV'),
	(155, 'Malawi', 'ملاوي', 'MW', 'MWI'),
	(156, 'Mexico', 'المكسيك', 'MX', 'MEX'),
	(157, 'Malaysia', 'ماليزيا', 'MY', 'MYS'),
	(158, 'Mozambique', 'موزامبيق', 'MZ', 'MOZ'),
	(159, 'Namibia', 'ناميبيا', 'NA', 'NAM'),
	(160, 'New Caledonia', 'كاليدونيا الجديدة', 'NC', 'NCL'),
	(161, 'Niger', 'النيجر', 'NE', 'NER'),
	(162, 'Norfolk Island', 'جزيرة نورفولك', 'NF', 'NFK'),
	(163, 'Nigeria', 'نيجيريا', 'NG', 'NGA'),
	(164, 'Nicaragua', 'نيكاراغوا', 'NI', 'NIC'),
	(165, 'Netherlands', 'هولندا', 'NL', 'NLD'),
	(166, 'Norway', 'النرويج', 'NO', 'NOR'),
	(167, 'Nepal', 'نيبال', 'NP', 'NPL'),
	(168, 'Nauru', 'ناورو', 'NR', 'NRU'),
	(169, 'Niue', 'نيوى', 'NU', 'NIU'),
	(170, 'New Zealand', 'نيوزيلندا', 'NZ', 'NZL'),
	(171, 'Oman', 'عمان', 'OM', 'OMN'),
	(172, 'Panama', 'بنما', 'PA', 'PAN'),
	(173, 'Peru', 'بيرو', 'PE', 'PER'),
	(174, 'French Polynesia', 'بولينزيا الفرنسية', 'PF', 'PYF'),
	(175, 'Papua New Guinea', 'الجديدة غينيا بابوا ', 'PG', 'PNG'),
	(176, 'Philippines', 'الفلبين', 'PH', 'PHL'),
	(177, 'Pakistan', 'باكستان', 'PK', 'PAK'),
	(178, 'Poland', 'بولندا', 'PL', 'POL'),
	(179, 'Saint Pierre and Miquelon', 'سان بيير وميكلون','PM', 'SPM'),
	(180, 'Pitcairn', 'جزر بيتكيرن', 'PN', 'PCN'),
	(181, 'Puerto Rico', 'بورتوريكو', 'PR', 'PRI'),
	(182, 'Palestine', 'فلسطين', 'PS', 'PSE'),
	(183, 'Portugal', 'البرتغال', 'PT', 'PRT'),
	(184, 'Palau', 'بالاو', 'PW', 'PLW'),
	(185, 'Paraguay', 'باراغواي', 'PY', 'PRY'),
	(186, 'Qatar', 'قطر', 'QA', 'QAT'),
	(187, 'Reunion', 'لا ريونيون', 'RE', 'REU'),
	(188, 'Romania', 'رومانيا', 'RO', 'ROU'),
	(189, 'Serbia', 'صربيا', 'RS', 'SRB'),
	(190, 'Russian Federation', 'الاتحاد الروسي ', 'RU', 'RUS'),
	(191, 'Rwanda', 'رواندا', 'RW', 'RWA'),
	(192, 'Saudi Arabia', 'السعودية العربية المملكة ', 'SA', 'SAU'),
	(193, 'Solomon Islands', 'جزر سليمان ', 'SB', 'SLB'),
	(194, 'Seychelles', 'سيشيل', 'SC', 'SYC'),
	(195, 'Sudan', 'السودان', 'SD', 'SDN'),
	(196, 'Sweden', 'السويد', 'SE', 'SWE'),
	(197, 'Singapore', 'سنغافورة', 'SG', 'SGP'),
	(198, 'Saint Helena', 'سانت هيلانة وأسينشين وتريستان دا كونا', 'SH', 'SHN'),
	(199, 'Slovenia', 'سلوفينيا', 'SI', 'SVN'),
	(200, 'Svalbard and Jan Mayen Islands', 'سفالبارد ويان ماين', 'SJ', 'SJM'),
	(201, 'Slovakia', 'سلوفاكيا', 'SK', 'SVK'),
	(202, 'Sierra Leone', 'سيراليون', 'SL', 'SLE'),
	(203, 'San Marino', 'مارينو سان ', 'SM', 'SMR'),
	(204, 'Senegal', 'السنغال', 'SN', 'SEN'),
	(205, 'Somalia', 'الصومال', 'SO', 'SOM'),
	(206, 'Suriname', 'سورينام', 'SR', 'SUR'),
	(207, 'Sao Tome and Principe', 'وبرنسيبي تومي سان ', 'ST', 'STP'),
	(208, 'El Salvador', 'السلفادور', 'SV', 'SLV'),
	(209, 'Syria', 'الجمهورية العربية السورية ', 'SY', 'SYR'),
	(210, 'Swaziland', 'سوازيلند', 'SZ', 'SWZ'),
	(211, 'Turks and Caicos Islands', 'جزر توركس وكايكوس', 'TC', 'TCA'),
	(212, 'Chad', 'تشاد', 'TD', 'TCD'),
	(213, 'French Southern Lands', 'أراض فرنسية جنوبية وأنتارتيكية','TF', 'ATF'),
	(214, 'Togo', 'توغو', 'TG', 'TGO'),
	(215, 'Thailand', 'تايلند', 'TH', 'THA'),
	(216, 'Tajikistan', 'طاجيكستان', 'TJ', 'TJK'),
	(217, 'Tokelau', 'منتسب عضو - توكيلاو ', 'TK', 'TKL'),
	(218, 'Timor-Leste', 'ليشتى تيمور- ','TL', 'TLS'),
	(219, 'Turkmenistan', 'تركمانستان', 'TM', 'TKM'),
	(220, 'Tunisia', 'تونس', 'TN', 'TUN'),
	(221, 'Tonga', 'تونغا', 'TO', 'TON'),
	(222, 'Turkey', 'تركيا', 'TR', 'TUR'),
	(223, 'Trinidad and Tobago', 'وتوباغو ترينيداد ', 'TT', 'TTO'),
	(224, 'Tuvalu', 'توفالو', 'TV', 'TUV'),
	(225, 'Taiwan', 'تايوان', 'TW', 'TWN'),
	(226, 'Tanzania', 'جمهورية تنزانيا المتحدة ', 'TZ', 'TZA'),
	(227, 'Ukraine', 'أوكرانيا', 'UA', 'UKR'),
	(228, 'Uganda', 'أوغندا', 'UG', 'UGA'),
	(229, 'United States Minor Outlying Islands', 'جزر الولايات المتحدة الصغيرة النائية', 'UM', 'UMI'),
	(230, 'United States of America', 'الأمريكية المتحدة الولايات ', 'US', 'USA'),
	(231, 'Uruguay', 'أوروغواي', 'UY', 'URY'),
	(232, 'Uzbekistan', 'أوزبكستان', 'UZ', 'UZB'),
	(233, 'Vatican City', 'الكرسي الرسولي ', 'VA', 'VAT'),
	(234, 'Saint Vincent and the Grenadines', 'سانت فنسنت وجزر غرينادين ', 'VC', 'VCT'),
	(235, 'Venezuela', 'البوليفارية - جمهورية - فنزويلا ', 'VE', 'VEN'),
	(236, 'Virgin Islands, British', 'جزر العذراء البريطانية', 'VG', 'VGB'),
	(237, 'Virgin Islands, U.S.', 'جزر العذراء الأمريكية', 'VI', 'VIR'),
	(238, 'Vietnam', 'فييت نام ','VN', 'VNM'),
	(239, 'Vanuatu', 'فانواتو', 'VU', 'VUT'),
	(240, 'Wallis and Futuna Islands', 'والس وفوتونا','WF', 'WLF'),
	(241, 'Samoa', 'ساموا', 'WS', 'WSM'),
	(242, 'Yemen', 'اليمن', 'YE', 'YEM'),
	(243, 'Mayotte', 'مايوت', 'YT', 'MYT'),
	(244, 'South Africa', 'أفريقيا جنوب ', 'ZA', 'ZAF'),
	(245, 'Zambia', 'زامبيا', 'ZM', 'ZMB'),
	(246, 'Zimbabwe', 'زمبابوي', 'ZW', 'ZWE');
	
	SET IDENTITY_INSERT countries OFF;
End