global using ARC.Application.Abstractions.Infrastructure;
global using ARC.Application.Abstractions.UserContext;
global using ARC.Application.Contracts.Persistence;
global using ARC.Application.Contracts.Persistence.UoW;
global using ARC.Application.Features.Auth.Commands.Login;
global using ARC.Domain.Entities;
global using ARC.Persistence.Identity;
global using Microsoft.Extensions.Logging;
global using Moq;